        
symfony_demo:
   path: /demo
   defaults: {_controller: "AcmeDemoBundle:Demo:index"}
   
   
#===================COMPETICIONES====================
listado_competiciones: #portada competiciones
   path: /admin/competiciones
   defaults: {_controller: "EasanlesAtletismoBundle:Competicion:listadoCompeticiones"}
crear_competicion:
   path: /admin/competiciones/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:Competicion:crearCompeticion"}
borrar_competicion:
   path: /admin/competiciones/borrar
   defaults: {_controller: "EasanlesAtletismoBundle:Competicion:borrarCompeticion"}
editar_competicion:
   path: /admin/competiciones/editar/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:Competicion:editarCompeticion"}
   requirements:
      id: \d+
ver_competicion:
   path: /admin/competiciones/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:Competicion:verCompeticion"}
   requirements:
      id: \d+
    

#======================PRUEBAS=======================
listado_pruebas:
   path: /admin/pruebas/{sidCom}
   defaults: {_controller: "EasanlesAtletismoBundle:Prueba:listadoPruebas"}
   requirements:
      sidCom: \d+
crear_prueba:
   path: /admin/pruebas/{sidCom}/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:Prueba:crearPrueba"}
   requirements:
      sidCom: \d+
borrar_prueba:
   path: /admin/pruebas/{sidCom}/borrar
   defaults: {_controller: "EasanlesAtletismoBundle:Prueba:borrarPrueba"}
   requirements:
      sidCom: \d+
editar_prueba:
   path: /admin/pruebas/{sidCom}/editar/{sidPru}
   defaults: {_controller: "EasanlesAtletismoBundle:Prueba:editarPrueba"}
   requirements:
      sidCom: \d+
      sidPru: \d+
listar_inscritos_prueba:
   path: /admin/pruebas/{sidCom}/listar
   defaults: {_controller: "EasanlesAtletismoBundle:Prueba:listarInscritosPrueba"}
   requirements:
      sidCom: \d+
            
    
#==================TIPOS DE PRUEBAS==================
listado_tipopruebaformato:
   path: /admin/configuracion/tipoprueba
   defaults: {_controller: "EasanlesAtletismoBundle:TipoPrueba:listadoTipoPruebaFormato"}
crear_tipopruebaformato:
   path: /admin/configuracion/tipoprueba/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:TipoPrueba:crearTipoPruebaFormato"}
borrar_tipopruebaformato:
   path: /admin/configuracion/tipoprueba/borrar
   defaults: {_controller: "EasanlesAtletismoBundle:TipoPrueba:borrarTipoPruebaFormato"}
editar_tipopruebaformato:
   path: /admin/configuracion/tipoprueba/editar/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:TipoPrueba:editarTipoPruebaFormato"}
   requirements:
      id: \d+
   
   
#=====================CATEGORIAS=====================
listado_categorias:
   path: /admin/configuracion/categoria
   defaults: {_controller: "EasanlesAtletismoBundle:Categoria:listadoCategorias"}
crear_categoria:
   path: /admin/configuracion/categoria/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:Categoria:crearCategoria"}
editar_categoria:
   path: /admin/configuracion/categoria/editar/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:Categoria:editarCategoria"}
   requirements:
      id: \d+
caducar_categoria:
   path: /admin/configuracion/categoria/caducar
   defaults: {_controller: "EasanlesAtletismoBundle:Categoria:caducarCategoria"}   


#=======================ATLETAS======================
listado_atletas:
   path: /admin/atletas
   defaults: {_controller: "EasanlesAtletismoBundle:Atleta:listadoAtletas"}
crear_atleta:
   path: /admin/atletas/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:Atleta:crearAtleta"}
ver_atleta:
   path: /admin/atletas/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:Atleta:verAtleta"}
   requirements:
      id: \d+
borrar_atleta:
   path: /admin/atleta/borrar
   defaults: {_controller: "EasanlesAtletismoBundle:Atleta:borrarAtleta"}   
editar_atleta:
   path: /admin/atleta/editar/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:Atleta:editarAtleta"}
   requirements:
      id: \d+
    
    
#====================INSCRIPCIONES===================
listado_inscripciones:
   path: /admin/competiciones/{sidCom}/inscripciones
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:listadoInscripciones"}
   requirements:
      sidCom: \d+
inscribir_atletas:
   path: /admin/competiciones/{sidCom}/inscribir
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:inscribirAtletas"}
   requirements:
      sidCom: \d+
inscribir_atletas_atletas:
   path: /admin/competiciones/{sidCom}/inscribir/atl
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:seleccionAtletas"}
   requirements:
      sidCom: \d+
inscribir_atletas_pruebas:
   path: /admin/competiciones/{sidCom}/inscribir/pru
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:seleccionPruebas"}
   requirements:
      sidCom: \d+
inscribir_atletas_pruebas_disponibles:
   path: /admin/competiciones/{sidCom}/inscribir/pru/{idAtl}
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:pruebasDisponibles"}
   requirements:
      sidCom: \d+
      idAtl: \d+
inscribir_atletas_confirmacion:
   path: /admin/competiciones/{sidCom}/inscribir/confirm
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:pantallaConfirmacion"}
   requirements:
      sidCom: \d+
inscribir_atletas_crear:
   path: /admin/competiciones/{sidCom}/inscribir/submit
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:crearInscripciones"}
   requirements:
      sidCom: \d+
editar_inscripcion:
   path: /admin/competiciones/{sidCom}/inscripciones/editar
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:editarInscripcion"}
   requirements:
      sidCom: \d+
borrar_inscripcion:
   path: /admin/competiciones/{sidCom}/inscripciones/borrar
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:borrarInscripcion"}
   requirements:
      sidCom: \d+


#===================PARTICIPACIONES==================
confirmar_participacion:
   path: /admin/competiciones/{sidCom}/participar
   defaults: {_controller: "EasanlesAtletismoBundle:Participacion:confirmarParticipacion"}
   requirements:
      sidCom: \d+
marcar_asistencia:
   path: /admin/competiciones/{sidCom}/asistencia
   defaults: {_controller: "EasanlesAtletismoBundle:Participacion:marcarAsistencia"}
   requirements:
      sidCom: \d+
      
      
#======================INTENTOS======================
registrar_intentos:
   path: /admin/marcas
   defaults: {_controller: "EasanlesAtletismoBundle:Intento:pantallaIntentos"}
intentos_pruebas:
   path: /admin/marcas/getpru
   defaults: {_controller: "EasanlesAtletismoBundle:Intento:obtenerPruebas"}
intentos_atletas:
   path: /admin/marcas/getatl
   defaults: {_controller: "EasanlesAtletismoBundle:Intento:obtenerAtletasInscritos"}
intentos_rondas:
   path: /admin/marcas/getron
   defaults: {_controller: "EasanlesAtletismoBundle:Intento:obtenerRondas"}
crear_intento:
   path: /admin/marcas/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:Intento:crearIntento"}
        
        
#======================INFORMES======================
#---------------------Resultados---------------------
pantalla_resultados:
   path: /informes/resultados
   defaults: {_controller: "EasanlesAtletismoBundle:Informes:pantallaResultados"}
resultados_pruebas:
   path: /informes/resultados/getpru
   defaults: {_controller: "EasanlesAtletismoBundle:Informes:obtenerPruebas"}
resultados_cartel:
   path: /informes/resultados/getcartel
   defaults: {_controller: "EasanlesAtletismoBundle:Informes:obtenerCartel"}
resultados_rondas:
   path: /informes/resultados/getron
   defaults: {_controller: "EasanlesAtletismoBundle:Informes:obtenerRondas"}
resultados_tabla:
   path: /informes/resultados/tabla
   defaults: {_controller: "EasanlesAtletismoBundle:Informes:obtenerTablaResultados"}
resultados_intentos:
   path: /informes/resultados/intentos
   defaults: {_controller: "EasanlesAtletismoBundle:Informes:mostrarIntentos"}

#----------------------Records-----------------------
pantalla_records_masc:
   path: /records/masculinos
   defaults: {_controller: "EasanlesAtletismoBundle:Informes:pantallaRecords", sexo: 0}
pantalla_records_fem:
   path: /records/femeninos
   defaults: {_controller: "EasanlesAtletismoBundle:Informes:pantallaRecords", sexo: 1}


#====================CONFIGURACION===================
configuracion: #portada configuracion
    path: /admin/configuracion
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:menu_configuracion"}
configuracion_cambiar_ajustes: #ajustes
    path: /admin/configuracion/ajustes
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:cambiarAjustes"}
configuracion_poblarbd: #poblar base de datos con datos de prueba
    path: /admin/configuracion/poblarbd
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:poblar_bd"}
configuracion_borrarbd: #borrar datos de la base de datos
    path: /admin/configuracion/borrarbd
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:borrar_bd"}
configuracion_rehacerbd: #drop tables y schema update
    path: /admin/configuracion/rehacerbd
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:rehacer_bd"}    
configuracion_limpiarcache: #Limpiar archivos cache
    path: /admin/configuracion/limpiarcache
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:limpiar_cache"}
configuracion_asseticdump:
    path: /admin/configuracion/asseticdump
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:assetic_dump"}     
    

#========================OTROS=======================    
homepage: #portada anonimos + users
    path: /
    defaults: {_controller: "EasanlesAtletismoBundle:Default:index", role: "user", name: "Anonimo"}
homepage_admin: #portada admins
    path: /admin/
    defaults: {_controller: "EasanlesAtletismoBundle:Default:index", role: "admin", name: "Admin"}
login:
    path: /login
    defaults: {_controller: "EasanlesAtletismoBundle:Default:login"}
login_check:
    path: /login_check
    defaults: {_controller: "EasanlesAtletismoBundle:Default:loginCheck"}
logout:
    path: /logout

    