#miembro: #informacion de un miembro
    #path:     /miembro/{id}
   #defaults: {_controller: "EasanlesAtletismoBundle:Miembro:mostrar", id: 1}
   # requirements:
       # id:  \d+ #numeros enteros
        
symfony_demo:
   path: /demo
   defaults: {_controller: "AcmeDemoBundle:Demo:index"}
   
   
#===================COMPETICIONES====================
listado_competiciones: #portada competiciones
   path: /competiciones
   defaults: {_controller: "EasanlesAtletismoBundle:Competicion:listadoCompeticiones"}
crear_competicion:
   path: /competiciones/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:Competicion:crearCompeticion"}
borrar_competicion:
   path: /competiciones/borrar
   defaults: {_controller: "EasanlesAtletismoBundle:Competicion:borrarCompeticion"}
editar_competicion:
   path: /competiciones/editar/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:Competicion:editarCompeticion"}
   requirements:
      id: \d+
ver_competicion:
   path: /competiciones/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:Competicion:verCompeticion"}
   requirements:
      id: \d+
    

#======================PRUEBAS=======================
listado_pruebas:
   path: /pruebas/{sidCom}
   defaults: {_controller: "EasanlesAtletismoBundle:Prueba:listadoPruebas"}
   requirements:
      sidCom: \d+
crear_prueba:
   path: /pruebas/{sidCom}/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:Prueba:crearPrueba"}
   requirements:
      sidCom: \d+
borrar_prueba:
   path: /pruebas/{sidCom}/borrar
   defaults: {_controller: "EasanlesAtletismoBundle:Prueba:borrarPrueba"}
   requirements:
      sidCom: \d+
editar_prueba:
   path: /pruebas/{sidCom}/editar/{sidPru}
   defaults: {_controller: "EasanlesAtletismoBundle:Prueba:editarPrueba"}
   requirements:
      sidCom: \d+
      sidPru: \d+
listar_inscritos_prueba:
   path: /pruebas/{sidCom}/listar
   defaults: {_controller: "EasanlesAtletismoBundle:Prueba:listarInscritosPrueba"}
   requirements:
      sidCom: \d+
            
    
#==================TIPOS DE PRUEBAS==================
listado_tipopruebaformato:
   path: /configuracion/tipoprueba
   defaults: {_controller: "EasanlesAtletismoBundle:TipoPrueba:listadoTipoPruebaFormato"}
crear_tipopruebaformato:
   path: /configuracion/tipoprueba/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:TipoPrueba:crearTipoPruebaFormato"}
borrar_tipopruebaformato:
   path: /configuracion/tipoprueba/borrar
   defaults: {_controller: "EasanlesAtletismoBundle:TipoPrueba:borrarTipoPruebaFormato"}
editar_tipopruebaformato:
   path: /configuracion/tipoprueba/editar/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:TipoPrueba:editarTipoPruebaFormato"}
   requirements:
      id: \d+
   
   
#=====================CATEGORIAS=====================
listado_categorias:
   path: /configuracion/categoria
   defaults: {_controller: "EasanlesAtletismoBundle:Categoria:listadoCategorias"}
crear_categoria:
   path: /configuracion/categoria/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:Categoria:crearCategoria"}
editar_categoria:
   path: /configuracion/categoria/editar/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:Categoria:editarCategoria"}
   requirements:
      id: \d+
caducar_categoria:
   path: /configuracion/categoria/caducar
   defaults: {_controller: "EasanlesAtletismoBundle:Categoria:caducarCategoria"}   


#=======================ATLETAS======================
listado_atletas:
   path: /atletas
   defaults: {_controller: "EasanlesAtletismoBundle:Atleta:listadoAtletas"}
crear_atleta:
   path: /atletas/nuevo
   defaults: {_controller: "EasanlesAtletismoBundle:Atleta:crearAtleta"}
ver_atleta:
   path: /atletas/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:Atleta:verAtleta"}
   requirements:
      id: \d+
borrar_atleta:
   path: /atleta/borrar
   defaults: {_controller: "EasanlesAtletismoBundle:Atleta:borrarAtleta"}   
editar_atleta:
   path: /atleta/editar/{id}
   defaults: {_controller: "EasanlesAtletismoBundle:Atleta:editarAtleta"}
   requirements:
      id: \d+
    
    
#====================INSCRIPCIONES===================
listado_inscripciones:
   path: /competiciones/{sidCom}/inscripciones
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:listadoInscripciones"}
   requirements:
      sidCom: \d+
inscribir_atletas:
   path: /competiciones/{sidCom}/inscribir
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:inscribirAtletas"}
   requirements:
      sidCom: \d+
inscribir_atletas_atletas:
   path: /competiciones/{sidCom}/inscribir/atl
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:seleccionAtletas"}
   requirements:
      sidCom: \d+
inscribir_atletas_pruebas:
   path: /competiciones/{sidCom}/inscribir/pru
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:seleccionPruebas"}
   requirements:
      sidCom: \d+
inscribir_atletas_pruebas_disponibles:
   path: /competiciones/{sidCom}/inscribir/pru/{idAtl}
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:pruebasDisponibles"}
   requirements:
      sidCom: \d+
      idAtl: \d+
inscribir_atletas_confirmacion:
   path: /competiciones/{sidCom}/inscribir/confirm
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:pantallaConfirmacion"}
   requirements:
      sidCom: \d+
inscribir_atletas_crear:
   path: /competiciones/{sidCom}/inscribir/submit
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:crearInscripciones"}
   requirements:
      sidCom: \d+
editar_inscripcion:
   path: /competiciones/{sidCom}/inscripciones/editar
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:editarInscripcion"}
   requirements:
      sidCom: \d+
borrar_inscripcion:
   path: /competiciones/{sidCom}/inscripciones/borrar
   defaults: {_controller: "EasanlesAtletismoBundle:Inscripcion:borrarInscripcion"}
   requirements:
      sidCom: \d+


#===================PARTICIPACIONES==================
confirmar_participacion:
   path: /competiciones/{sidCom}/participar
   defaults: {_controller: "EasanlesAtletismoBundle:Participacion:confirmarParticipacion"}
   requirements:
      sidCom: \d+
marcar_asistencia:
   path: /competiciones/{sidCom}/asistencia
   defaults: {_controller: "EasanlesAtletismoBundle:Participacion:marcarAsistencia"}
   requirements:
      sidCom: \d+
     

#====================CONFIGURACION===================
configuracion: #portada configuracion
    path: /configuracion
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:menu_configuracion"}
configuracion_cambiar_ajustes: #ajustes
    path: /configuracion/ajustes
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:cambiarAjustes"}
configuracion_poblarbd: #poblar base de datos con datos de prueba
    path: /configuracion/poblarbd
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:poblar_bd"}
configuracion_borrarbd: #borrar datos de la base de datos
    path: /configuracion/borrarbd
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:borrar_bd"}
configuracion_rehacerbd: #drop tables y schema update
    path: /configuracion/rehacerbd
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:rehacer_bd"}    
configuracion_limpiarcache: #Limpiar archivos cache
    path: /configuracion/limpiarcache
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:limpiar_cache"}
configuracion_asseticdump:
    path: /configuracion/asseticdump
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:assetic_dump"}     
    
    
homepage: #portada
    path: /{name}
    defaults: {_controller: "EasanlesAtletismoBundle:Default:index", name: "Anonimo"}
    
