miembro: #informacion de un miembro
    path:     /miembro/{id}
    defaults: {_controller: "EasanlesAtletismoBundle:Miembro:mostrar", id: 1}
    requirements:
        id:  \d+ #numeros enteros
        
symfony_demo:
   path: /demo
   defaults: {_controller: "AcmeDemoBundle:Demo:index"}
    
listado_competiciones: #portada competiciones
    path: /competiciones
    defaults: {_controller: "EasanlesAtletismoBundle:Competicion:listado_competiciones"}
    
    
    
configuracion: #portada configuracion
    path: /configuracion
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:menu_configuracion"}
    
configuracion_poblarbd: #poblar base de datos con datos de prueba
    path: /configuracion/poblarbd
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:poblar_bd"}
    
configuracion_borrarbd: #borrar datos de la base de datos
    path: /configuracion/borrarbd
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:borrar_bd"}
    
configuracion_rehacerbd: #drop tables y schema update
    path: /configuracion/rehacerbd
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:rehacer_bd"}    
    
configuracion_limpiarcache: #Limpiar archivos cache
    path: /configuracion/limpiarcache
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:limpiar_cache"}
    
configuracion_asseticdump:
    path: /configuracion/asseticdump
    defaults: {_controller: "EasanlesAtletismoBundle:Configuracion:assetic_dump"}     
    
    
homepage: #portada
    path: /{name}
    defaults: {_controller: "EasanlesAtletismoBundle:Default:index", name: "Anonimo"}
    
