services:
#  em_com_service:
#    class: Easanles\AtletismoBundle\Entity\Competicion
#    arguments: ["@doctrine.orm.default_entity_manager"]

    
#  easanles_atletismo.example:
#     class: Easanles\AtletismoBundle\Example
#     arguments: [@service_id, "plain_value", %parameter%]
     