
# Copyright (c) 2016 Eduardo Alonso Sanlés
# Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php

Easanles\AtletismoBundle\Entity\Competicion:
  properties:
     nombre:
        - NotBlank: 
           message: Este campo no debe estar en blanco
     temp:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - GreaterThan:
           value: 0
           message: Introduza un valor mayor que cero
        - NotBlank: 
           message: Este campo no debe estar en blanco
     fecha:
        - Type:
           type: DateTime
           message: Este dato no es una fecha válida
     web:
        - Url:
           message: Este dato no es una dirección url válida
     email:
        - Email:
           message: Este dato no es una dirección de correo electrónico válido
     cartelFile:
        - Image: 
           mimeTypesMessage: El archivo recibido no es un archivo de imagen

Easanles\AtletismoBundle\Entity\TipoPruebaFormato:
  properties:
     nombre:
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     unidades:
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     numint:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - GreaterThan:
           value: 0
           message: Debe tener al menos 1 intento por prueba
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco

Easanles\AtletismoBundle\Entity\TipoPruebaModalidad:
  properties:
     sexo:
        - Type: 
           type: Integer
           message: Dato no válido
        - GreaterThanOrEqual:
           value: 0
           message: Dato no válido
        - LessThanOrEqual:
           value: 2
           message: Dato no válido
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     entorno:
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
           
Easanles\AtletismoBundle\Entity\Prueba:
  properties:
     id:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     idCat:
        - NotNull: 
           message: Seleccione una categoría
     coste:
        - Type: 
           type: Float
           message: Este valor debe ser un número entero o con decimales
        - GreaterThanOrEqual:
           value: 0
           message: No se puede asignar un precio negativo
        - NotBlank: 
           message: Introduzca el precio de la prueba
           
Easanles\AtletismoBundle\Entity\Ronda:
  properties:
     num:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - GreaterThan:
           value: 0
           message: El número de ronda debe ser mayor de cero
        - NotBlank: 
           message: Introduzca el número de ronda

Easanles\AtletismoBundle\Entity\Categoria:
  properties:
     nombre:
        - NotBlank: 
           message: Este campo no debe estar en blanco
     edadMax:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - GreaterThan:
           value: 0
           message: Introduzca un valor mayor que 0 o deje en blanco
     tIniVal:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - GreaterThan:
           value: 0
           message: Introduzca un valor mayor que 0
        - NotBlank: 
           message: Este campo no debe estar en blanco
     tFinVal:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - GreaterThan:
           value: 0
           message: Introduzca un valor mayor que 0
        
Easanles\AtletismoBundle\Entity\Atleta:
  properties:
     nombre:
        - NotBlank: 
           message: Este campo no debe estar en blanco
     apellidos:
        - NotBlank: 
           message: Este campo no debe estar en blanco
     fnac:
        - Type:
           type: DateTime
           message: Este dato no es una fecha válida
     sexo:
        - NotNull: 
           message: Este dato no debe ser nulo
     email:
        - Email:
           message: Este dato no es una dirección de correo electrónico válido
     fotoFile:
        - Image: 
           mimeTypesMessage: El archivo recibido no es un archivo de imagen      

Easanles\AtletismoBundle\Entity\Inscripcion:
  properties:
     idAtl:
        - NotNull: 
           message: No puede ser nulo
     sidPru:
        - NotNull: 
           message: No puede ser nulo
     coste:
        - Type: 
           type: Float
           message: Este valor debe ser un número entero o con decimales
        - GreaterThanOrEqual:
           value: 0
           message: No se puede asignar un precio negativo
        - NotBlank: 
           message: Introduzca el precio de la prueba
  
Easanles\AtletismoBundle\Entity\Usuario:
  properties:
     nombre:
        - NotBlank: 
           message: Este campo no debe estar en blanco
     contra:
        - NotBlank: 
           message: Este campo no debe estar en blanco
     rol:
        - NotNull: 
           message: Seleccione un rol
           