

Easanles\AtletismoBundle\Entity\Competicion:
  properties:
     nombre:
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     temp:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     fecha:
        - Type:
           type: DateTime
           message: Este dato no es una fecha válida
     web:
        - Url:
           message: Este dato no es una dirección url válida
     email:
        - Email:
           message: Este dato no es una dirección de correo electrónico válido
     cartelFile:
        - Image: 
           mimeTypesMessage: El archivo recibido no es un archivo de imagen

Easanles\AtletismoBundle\Entity\TipoPruebaFormato:
  properties:
     nombre:
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     unidades:
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     numint:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - GreaterThan:
           value: 0
           message: Debe tener al menos 1 intento por prueba
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco

Easanles\AtletismoBundle\Entity\TipoPruebaModalidad:
  properties:
     sexo:
        - Type: 
           type: Integer
           message: Dato no válido
        - GreaterThanOrEqual:
           value: 0
           message: Dato no válido
        - LessThanOrEqual:
           value: 2
           message: Dato no válido
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     entorno:
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
           
Easanles\AtletismoBundle\Entity\Prueba:
  properties:
     id:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     ronda:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - GreaterThanOrEqual:
           value: 0
           message: Dato no válido
        - NotNull: 
           message: Este dato no debe ser nulo
        - NotBlank: 
           message: Este campo no debe estar en blanco
     idCat:
        - NotNull: 
           message: Seleccione una categoría

Easanles\AtletismoBundle\Entity\Categoria:
  properties:
     nombre:
        - NotBlank: 
           message: Este campo no debe estar en blanco
     edadMax:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - GreaterThan:
           value: 0
           message: Introduzca un valor mayor a 0 o deje en blanco
     tIniVal:
        - Type: 
           type: Integer
           message: Este valor debe ser un número entero
        - GreaterThan:
           value: 0
           message: Introduzca un valor mayor a 0
        - NotBlank: 
           message: Este campo no debe estar en blanco
        
Easanles\AtletismoBundle\Entity\Atleta:
  properties:
     nombre:
        - NotBlank: 
           message: Este campo no debe estar en blanco
     apellidos:
        - NotBlank: 
           message: Este campo no debe estar en blanco
     fnac:
        - Type:
           type: DateTime
           message: Este dato no es una fecha válida
     sexo:
        - NotNull: 
           message: Este dato no debe ser nulo
     email:
        - Email:
           message: Este dato no es una dirección de correo electrónico válido
     fotoFile:
        - Image: 
           mimeTypesMessage: El archivo recibido no es un archivo de imagen      
  