security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext #Para borrar
        Easanles\AtletismoBundle\Entity\Usuario:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:  #Para borrar
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        db_provider:
            entity:
                class: EasanlesAtletismoBundle:Usuario
                property: nombre

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        secured_area:
            anonymous: ~
#            provider: in_memory  #Para borrar
            provider: db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                require_previous_session: false
            remember_me:
                key:   '%secret%'
            logout:
                path: /logout
                target: /

    access_control:
        #Descomentar la siguiente linea para activar la conexion segura al enviar credenciales.
        #HTTPS debe estar correctamente configurado en el servidor Apache
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN }
