<?php

namespace Easanles\AtletismoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MiembroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiembroRepository extends EntityRepository
{
}
